apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-deployment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gabimirea/aks-platform-engineering.git
    targetRevision: main
    #path: gitops/apps/_empty
    path: gitops/apps/myapp
    directory:
    #  include: "{AKS1-CNPG-Operator-ArgoApp.yaml,AKS1-CNPG-Demo-ArgoApp.yaml,AKS1-CNPG-Dev-ArgoApp.yaml,AKS1-CNPG-UAT-ArgoApp.yaml,AKS1-CNPG-Prod-ArgoApp.yaml,AKSStoreDemoArgoApp.yaml}"
    #  include: "{AKS1-CNPG-Prod-ArgoApp.yaml}"
    #  include: "{AKS1-CNPG-UAT-ArgoApp.yaml}"
      include: "{AKS1-CNPG-Dev-ArgoApp.yaml,AKS1-CNPG-UAT-ArgoApp.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
